"""
Constellation Generator

Generate Walker constellation satellite shells and fetch live orbital data
for orbit simulation tools. Includes J2-corrected propagation, topocentric
observation geometry, access window prediction, coverage analysis,
time-domain revisit analysis, parametric trade studies,
atmospheric drag modeling, orbit lifetime prediction, station-keeping
delta-V budgets, conjunction/collision probability assessment, solar
ephemeris, eclipse prediction, orbit transfer maneuvers, deorbit
compliance, orbit design utilities, derived orbital properties (velocity,
energy, RSW decomposition, LTAN, Sun-sync verification, state-to-elements),
pass analysis (Doppler, visual magnitude, contact statistics, data downlink),
and constellation-level metrics (coverage/revisit/eclipse statistics,
N-1 redundancy, constellation score, thermal cycling, ground network,
deployment phasing).
"""

from constellation_generator.domain.orbital_mechanics import (
    OrbitalConstants,
    kepler_to_cartesian,
    sso_inclination_deg,
    j2_raan_rate,
    j2_arg_perigee_rate,
    j2_mean_motion_correction,
)
from constellation_generator.domain.constellation import (
    ShellConfig,
    Satellite,
    generate_walker_shell,
    generate_sso_band_configs,
)
from constellation_generator.domain.serialization import (
    format_position,
    format_velocity,
    build_satellite_entity,
)
from constellation_generator.domain.omm import (
    OrbitalElements,
    parse_omm_record,
)
from constellation_generator.domain.coordinate_frames import (
    gmst_rad,
    eci_to_ecef,
    ecef_to_geodetic,
    geodetic_to_ecef,
)
from constellation_generator.domain.ground_track import (
    AscendingNodePass,
    GroundTrackCrossing,
    GroundTrackPoint,
    compute_ground_track,
    compute_ground_track_numerical,
    find_ascending_nodes,
    find_ground_track_crossings,
)
from constellation_generator.domain.propagation import (
    OrbitalState,
    derive_orbital_state,
    propagate_to,
    propagate_ecef_to,
)
from constellation_generator.domain.observation import (
    GroundStation,
    Observation,
    compute_observation,
)
from constellation_generator.domain.access_windows import (
    AccessWindow,
    compute_access_windows,
)
from constellation_generator.domain.coverage import (
    CoveragePoint,
    compute_coverage_snapshot,
)
from constellation_generator.domain.revisit import (
    GridPoint,
    PointRevisitResult,
    CoverageResult,
    compute_revisit,
    compute_single_coverage_fraction,
)
from constellation_generator.domain.trade_study import (
    WalkerConfig,
    TradePoint,
    TradeStudyResult,
    run_walker_trade_study,
    generate_walker_configs,
    pareto_front_indices,
)
from constellation_generator.domain.atmosphere import (
    AtmosphereModel,
    DragConfig,
    atmospheric_density,
    drag_acceleration,
    semi_major_axis_decay_rate,
)
from constellation_generator.domain.lifetime import (
    DecayPoint,
    OrbitLifetimeResult,
    compute_orbit_lifetime,
    compute_altitude_at_time,
)
from constellation_generator.domain.station_keeping import (
    StationKeepingConfig,
    StationKeepingBudget,
    drag_compensation_dv_per_year,
    plane_maintenance_dv_per_year,
    tsiolkovsky_dv,
    propellant_mass_for_dv,
    compute_station_keeping_budget,
)
from constellation_generator.domain.conjunction import (
    PositionCovariance,
    ConjunctionEvent,
    screen_conjunctions,
    screen_conjunctions_numerical,
    refine_tca,
    compute_b_plane,
    foster_max_collision_probability,
    collision_probability_2d,
    assess_conjunction,
)
from constellation_generator.domain.solar import (
    SunPosition,
    sun_position_eci,
    solar_declination_rad,
)
from constellation_generator.domain.eclipse import (
    BetaAngleHistory,
    BetaAngleSnapshot,
    EclipseType,
    EclipseEvent,
    is_eclipsed,
    compute_beta_angle,
    compute_beta_angle_history,
    compute_eclipse_windows,
    eclipse_fraction,
    predict_eclipse_seasons,
)
from constellation_generator.domain.maneuvers import (
    ManeuverBurn,
    TransferPlan,
    hohmann_transfer,
    bielliptic_transfer,
    plane_change_dv,
    combined_plane_and_altitude,
    phasing_maneuver,
    add_propellant_estimate,
)
from constellation_generator.domain.deorbit import (
    DeorbitRegulation,
    DeorbitAssessment,
    assess_deorbit_compliance,
)
from constellation_generator.domain.orbit_design import (
    SSODesign,
    FrozenOrbitDesign,
    RepeatGroundTrackDesign,
    design_sso_orbit,
    design_frozen_orbit,
    design_repeat_ground_track,
)
from constellation_generator.domain.sensor import (
    SensorType,
    SensorConfig,
    GroundFootprint,
    SensorAccessResult,
    compute_swath_width,
    compute_nadir_footprint,
    is_in_sensor_fov,
    compute_sensor_coverage,
)
from constellation_generator.domain.numerical_propagation import (
    ForceModel,
    PropagationStep,
    NumericalPropagationResult,
    TwoBodyGravity,
    J2Perturbation,
    J3Perturbation,
    AtmosphericDragForce,
    SolarRadiationPressureForce,
    rk4_step,
    propagate_numerical,
)
from constellation_generator.domain.orbit_properties import (
    OrbitalVelocity,
    EnergyMomentum,
    SunSyncCheck,
    GroundTrackRepeat,
    ElementSnapshot,
    ElementHistory,
    compute_orbital_velocity,
    compute_energy_momentum,
    check_sun_synchronous,
    compute_rsw_velocity,
    compute_ltan,
    state_vector_to_elements,
    compute_ground_track_repeat,
    compute_element_history,
)
from constellation_generator.domain.inter_satellite_links import (
    ISLLink,
    ISLTopology,
    is_earth_blocked,
    compute_isl_link,
    compute_isl_topology,
)
from constellation_generator.domain.dilution_of_precision import (
    DOPResult,
    DOPGridPoint,
    compute_dop,
    compute_dop_grid,
)
from constellation_generator.domain.pass_analysis import (
    DopplerResult,
    PassClassification,
    ContactSummary,
    DataDownlinkEstimate,
    compute_doppler_shift,
    classify_pass,
    compute_contact_summary,
    estimate_data_downlink,
    compute_visible_magnitude,
)
from constellation_generator.domain.constellation_metrics import (
    CoverageStatistics,
    RevisitStatistics,
    EclipseStatistics,
    RedundancyResult,
    ConstellationScore,
    ThermalCycling,
    GroundNetworkMetrics,
    DeploymentPhasing,
    compute_coverage_statistics,
    compute_revisit_statistics,
    compute_eclipse_statistics,
    compute_n_minus_1_redundancy,
    compute_constellation_score,
    compute_thermal_cycling,
    compute_ground_network_metrics,
    compute_deployment_phasing,
)
from constellation_generator.domain.relative_motion import (
    RelativeState,
    CWTrajectory,
    cw_propagate_state,
    cw_propagate,
    compute_relative_state,
    is_passively_safe,
)
from constellation_generator.domain.link_budget import (
    LinkConfig,
    LinkBudgetResult,
    free_space_path_loss_db,
    compute_link_budget,
    compute_isl_link_budgets,
)
from constellation_generator.domain.third_body import (
    MoonPosition,
    moon_position_eci,
    SolarThirdBodyForce,
    LunarThirdBodyForce,
)
from constellation_generator.domain.torques import (
    InertiaTensor,
    TorqueResult,
    AerodynamicTorqueResult,
    compute_gravity_gradient_torque,
    compute_aerodynamic_torque,
)
from constellation_generator.domain.radiation import (
    RadiationEnvironment,
    OrbitRadiationSummary,
    compute_l_shell,
    compute_radiation_environment,
    compute_orbit_radiation_summary,
)
from constellation_generator.domain.maintenance_planning import (
    ElementPerturbation,
    PerturbationBudget,
    MaintenanceBurn,
    MaintenanceSchedule,
    compute_perturbation_budget,
    compute_maintenance_schedule,
)
from constellation_generator.domain.environment_analysis import (
    ThermalMonth,
    SeasonalThermalProfile,
    DoseSnapshot,
    SeasonalDoseProfile,
    RadiationLTANPoint,
    RadiationLTANResult,
    EclipseFreeLTANPoint,
    EclipseFreeResult,
    TorqueBoundary,
    TorqueTimingResult,
    compute_seasonal_thermal_profile,
    compute_seasonal_dose_profile,
    compute_radiation_optimized_ltan,
    compute_eclipse_free_windows,
    compute_worst_case_torque_timing,
)
from constellation_generator.domain.coverage_optimization import (
    QualityCoveragePoint,
    QualityCoverageResult,
    CrossingRevisitResult,
    CompliantTradePoint,
    CompliantTradeResult,
    EOLTANPoint,
    EOLTANOptimization,
    StationCandidate,
    GroundStationOptimization,
    compute_quality_weighted_coverage,
    compute_crossing_revisit,
    compute_compliant_trade_study,
    compute_optimal_eo_ltan,
    compute_optimal_ground_stations,
)
from constellation_generator.domain.communication_analysis import (
    DegradedLink,
    EclipseDegradedTopology,
    PassDataPoint,
    PassThroughput,
    ISLDistancePrediction,
    NetworkCapacitySnapshot,
    NetworkCapacityTimeline,
    compute_eclipse_degraded_topology,
    compute_pass_data_throughput,
    predict_isl_distances,
    compute_network_capacity_timeline,
)
from constellation_generator.domain.conjunction_management import (
    ConjunctionAction,
    ConjunctionTriage,
    AvoidanceManeuver,
    ConjunctionDecision,
    triage_conjunction,
    compute_avoidance_maneuver,
    run_conjunction_decision_pipeline,
)
from constellation_generator.domain.mission_analysis import (
    PropellantPoint,
    PropellantProfile,
    HealthSnapshot,
    HealthTimeline,
    AltitudeTradePoint,
    AltitudeOptimization,
    MissionCostMetric,
    compute_propellant_profile,
    compute_health_timeline,
    compute_optimal_altitude,
    compute_mission_cost_metric,
)
from constellation_generator.domain.linalg import (
    EigenDecomposition,
    DFTResult,
    mat_zeros,
    mat_identity,
    mat_multiply,
    mat_transpose,
    mat_add,
    mat_scale,
    mat_eigenvalues_symmetric,
    mat_determinant,
    mat_inverse,
    mat_trace,
    naive_dft,
)
from constellation_generator.domain.graph_analysis import (
    TopologyResilience,
    FragmentationEvent,
    FragmentationTimeline,
    compute_topology_resilience,
    compute_fragmentation_timeline,
)
from constellation_generator.domain.information_theory import (
    EclipseChannelCapacity,
    CoverageSpectrum,
    MarginalSatelliteValue,
    compute_eclipse_channel_capacity,
    compute_coverage_spectrum,
    compute_marginal_satellite_value,
)
from constellation_generator.domain.control_analysis import (
    ControllabilityAnalysis,
    compute_cw_controllability,
)
from constellation_generator.domain.statistical_analysis import (
    CollisionProbabilityAnalytical,
    LifetimeSurvivalCurve,
    MissionAvailabilityProfile,
    RadiationEclipseCorrelation,
    compute_analytical_collision_probability,
    compute_lifetime_survival_curve,
    compute_mission_availability,
    compute_radiation_eclipse_correlation,
)
from constellation_generator.domain.design_optimization import (
    PositioningInformationMetric,
    CoverageDriftAnalysis,
    MassEfficiencyPoint,
    MassEfficiencyFrontier,
    compute_positioning_information,
    compute_coverage_drift,
    compute_mass_efficiency_frontier,
)
from constellation_generator.domain.spectral_topology import (
    FragmentationSpectralAnalysis,
    EclipseSpectralInvariant,
    ProximitySpectralResult,
    compute_fragmentation_spectrum,
    compute_eclipse_spectral_invariant,
    compute_proximity_spectrum,
)
from constellation_generator.domain.constellation_operability import (
    ConstellationOperabilityIndex,
    CommonCauseFailureResult,
    compute_operability_index,
    compute_common_cause_failure,
)
from constellation_generator.domain.mission_economics import (
    SurvivalWeightedEfficiencyPoint,
    SurvivalWeightedMassFrontier,
    ReliabilityWeightedCostPoint,
    ReliabilityWeightedCostProfile,
    compute_survival_weighted_frontier,
    compute_reliability_weighted_cost,
)
from constellation_generator.domain.multi_objective_design import (
    ParetoPoint,
    ParetoSurface,
    EntropyCollisionEfficiency,
    compute_pareto_surface,
    compute_entropy_collision_efficiency,
)
from constellation_generator.domain.cascade_analysis import (
    CascadeIndicator,
    compute_cascade_indicator,
)

__version__ = "1.18.0"

__all__ = [
    "OrbitalConstants",
    "kepler_to_cartesian",
    "sso_inclination_deg",
    "j2_raan_rate",
    "j2_arg_perigee_rate",
    "j2_mean_motion_correction",
    "ShellConfig",
    "Satellite",
    "generate_walker_shell",
    "generate_sso_band_configs",
    "format_position",
    "format_velocity",
    "build_satellite_entity",
    "OrbitalElements",
    "parse_omm_record",
    "gmst_rad",
    "eci_to_ecef",
    "ecef_to_geodetic",
    "geodetic_to_ecef",
    "AscendingNodePass",
    "GroundTrackCrossing",
    "GroundTrackPoint",
    "compute_ground_track",
    "compute_ground_track_numerical",
    "find_ascending_nodes",
    "find_ground_track_crossings",
    "OrbitalState",
    "derive_orbital_state",
    "propagate_to",
    "propagate_ecef_to",
    "GroundStation",
    "Observation",
    "compute_observation",
    "AccessWindow",
    "compute_access_windows",
    "CoveragePoint",
    "compute_coverage_snapshot",
    "GridPoint",
    "PointRevisitResult",
    "CoverageResult",
    "compute_revisit",
    "compute_single_coverage_fraction",
    "WalkerConfig",
    "TradePoint",
    "TradeStudyResult",
    "run_walker_trade_study",
    "generate_walker_configs",
    "pareto_front_indices",
    "AtmosphereModel",
    "DragConfig",
    "atmospheric_density",
    "drag_acceleration",
    "semi_major_axis_decay_rate",
    "DecayPoint",
    "OrbitLifetimeResult",
    "compute_orbit_lifetime",
    "compute_altitude_at_time",
    "StationKeepingConfig",
    "StationKeepingBudget",
    "drag_compensation_dv_per_year",
    "plane_maintenance_dv_per_year",
    "tsiolkovsky_dv",
    "propellant_mass_for_dv",
    "compute_station_keeping_budget",
    "PositionCovariance",
    "ConjunctionEvent",
    "screen_conjunctions",
    "screen_conjunctions_numerical",
    "refine_tca",
    "compute_b_plane",
    "foster_max_collision_probability",
    "collision_probability_2d",
    "assess_conjunction",
    "SunPosition",
    "sun_position_eci",
    "solar_declination_rad",
    "BetaAngleHistory",
    "BetaAngleSnapshot",
    "EclipseType",
    "EclipseEvent",
    "is_eclipsed",
    "compute_beta_angle",
    "compute_beta_angle_history",
    "compute_eclipse_windows",
    "eclipse_fraction",
    "predict_eclipse_seasons",
    "ManeuverBurn",
    "TransferPlan",
    "hohmann_transfer",
    "bielliptic_transfer",
    "plane_change_dv",
    "combined_plane_and_altitude",
    "phasing_maneuver",
    "add_propellant_estimate",
    "DeorbitRegulation",
    "DeorbitAssessment",
    "assess_deorbit_compliance",
    "SSODesign",
    "FrozenOrbitDesign",
    "RepeatGroundTrackDesign",
    "design_sso_orbit",
    "design_frozen_orbit",
    "design_repeat_ground_track",
    "SensorType",
    "SensorConfig",
    "GroundFootprint",
    "SensorAccessResult",
    "compute_swath_width",
    "compute_nadir_footprint",
    "is_in_sensor_fov",
    "compute_sensor_coverage",
    "ForceModel",
    "PropagationStep",
    "NumericalPropagationResult",
    "TwoBodyGravity",
    "J2Perturbation",
    "J3Perturbation",
    "AtmosphericDragForce",
    "SolarRadiationPressureForce",
    "rk4_step",
    "propagate_numerical",
    # orbit_properties
    "OrbitalVelocity",
    "EnergyMomentum",
    "SunSyncCheck",
    "GroundTrackRepeat",
    "ElementSnapshot",
    "ElementHistory",
    "compute_orbital_velocity",
    "compute_energy_momentum",
    "check_sun_synchronous",
    "compute_rsw_velocity",
    "compute_ltan",
    "state_vector_to_elements",
    "compute_ground_track_repeat",
    "compute_element_history",
    # inter_satellite_links
    "ISLLink",
    "ISLTopology",
    "is_earth_blocked",
    "compute_isl_link",
    "compute_isl_topology",
    # dilution_of_precision
    "DOPResult",
    "DOPGridPoint",
    "compute_dop",
    "compute_dop_grid",
    # pass_analysis
    "DopplerResult",
    "PassClassification",
    "ContactSummary",
    "DataDownlinkEstimate",
    "compute_doppler_shift",
    "classify_pass",
    "compute_contact_summary",
    "estimate_data_downlink",
    "compute_visible_magnitude",
    # constellation_metrics
    "CoverageStatistics",
    "RevisitStatistics",
    "EclipseStatistics",
    "RedundancyResult",
    "ConstellationScore",
    "ThermalCycling",
    "GroundNetworkMetrics",
    "DeploymentPhasing",
    "compute_coverage_statistics",
    "compute_revisit_statistics",
    "compute_eclipse_statistics",
    "compute_n_minus_1_redundancy",
    "compute_constellation_score",
    "compute_thermal_cycling",
    "compute_ground_network_metrics",
    "compute_deployment_phasing",
    # relative_motion
    "RelativeState",
    "CWTrajectory",
    "cw_propagate_state",
    "cw_propagate",
    "compute_relative_state",
    "is_passively_safe",
    # link_budget
    "LinkConfig",
    "LinkBudgetResult",
    "free_space_path_loss_db",
    "compute_link_budget",
    "compute_isl_link_budgets",
    # third_body
    "MoonPosition",
    "moon_position_eci",
    "SolarThirdBodyForce",
    "LunarThirdBodyForce",
    # torques
    "InertiaTensor",
    "TorqueResult",
    "AerodynamicTorqueResult",
    "compute_gravity_gradient_torque",
    "compute_aerodynamic_torque",
    # radiation
    "RadiationEnvironment",
    "OrbitRadiationSummary",
    "compute_l_shell",
    "compute_radiation_environment",
    "compute_orbit_radiation_summary",
    # maintenance_planning
    "ElementPerturbation",
    "PerturbationBudget",
    "MaintenanceBurn",
    "MaintenanceSchedule",
    "compute_perturbation_budget",
    "compute_maintenance_schedule",
    # environment_analysis
    "ThermalMonth",
    "SeasonalThermalProfile",
    "DoseSnapshot",
    "SeasonalDoseProfile",
    "RadiationLTANPoint",
    "RadiationLTANResult",
    "EclipseFreeLTANPoint",
    "EclipseFreeResult",
    "TorqueBoundary",
    "TorqueTimingResult",
    "compute_seasonal_thermal_profile",
    "compute_seasonal_dose_profile",
    "compute_radiation_optimized_ltan",
    "compute_eclipse_free_windows",
    "compute_worst_case_torque_timing",
    # coverage_optimization
    "QualityCoveragePoint",
    "QualityCoverageResult",
    "CrossingRevisitResult",
    "CompliantTradePoint",
    "CompliantTradeResult",
    "EOLTANPoint",
    "EOLTANOptimization",
    "StationCandidate",
    "GroundStationOptimization",
    "compute_quality_weighted_coverage",
    "compute_crossing_revisit",
    "compute_compliant_trade_study",
    "compute_optimal_eo_ltan",
    "compute_optimal_ground_stations",
    # communication_analysis
    "DegradedLink",
    "EclipseDegradedTopology",
    "PassDataPoint",
    "PassThroughput",
    "ISLDistancePrediction",
    "NetworkCapacitySnapshot",
    "NetworkCapacityTimeline",
    "compute_eclipse_degraded_topology",
    "compute_pass_data_throughput",
    "predict_isl_distances",
    "compute_network_capacity_timeline",
    # conjunction_management
    "ConjunctionAction",
    "ConjunctionTriage",
    "AvoidanceManeuver",
    "ConjunctionDecision",
    "triage_conjunction",
    "compute_avoidance_maneuver",
    "run_conjunction_decision_pipeline",
    # mission_analysis
    "PropellantPoint",
    "PropellantProfile",
    "HealthSnapshot",
    "HealthTimeline",
    "AltitudeTradePoint",
    "AltitudeOptimization",
    "MissionCostMetric",
    "compute_propellant_profile",
    "compute_health_timeline",
    "compute_optimal_altitude",
    "compute_mission_cost_metric",
    # linalg
    "EigenDecomposition",
    "DFTResult",
    "mat_zeros",
    "mat_identity",
    "mat_multiply",
    "mat_transpose",
    "mat_add",
    "mat_scale",
    "mat_eigenvalues_symmetric",
    "mat_determinant",
    "mat_inverse",
    "mat_trace",
    "naive_dft",
    # graph_analysis
    "TopologyResilience",
    "FragmentationEvent",
    "FragmentationTimeline",
    "compute_topology_resilience",
    "compute_fragmentation_timeline",
    # information_theory
    "EclipseChannelCapacity",
    "CoverageSpectrum",
    "MarginalSatelliteValue",
    "compute_eclipse_channel_capacity",
    "compute_coverage_spectrum",
    "compute_marginal_satellite_value",
    # control_analysis
    "ControllabilityAnalysis",
    "compute_cw_controllability",
    # statistical_analysis
    "CollisionProbabilityAnalytical",
    "LifetimeSurvivalCurve",
    "MissionAvailabilityProfile",
    "RadiationEclipseCorrelation",
    "compute_analytical_collision_probability",
    "compute_lifetime_survival_curve",
    "compute_mission_availability",
    "compute_radiation_eclipse_correlation",
    # design_optimization
    "PositioningInformationMetric",
    "CoverageDriftAnalysis",
    "MassEfficiencyPoint",
    "MassEfficiencyFrontier",
    "compute_positioning_information",
    "compute_coverage_drift",
    "compute_mass_efficiency_frontier",
    # spectral_topology
    "FragmentationSpectralAnalysis",
    "EclipseSpectralInvariant",
    "ProximitySpectralResult",
    "compute_fragmentation_spectrum",
    "compute_eclipse_spectral_invariant",
    "compute_proximity_spectrum",
    # constellation_operability
    "ConstellationOperabilityIndex",
    "CommonCauseFailureResult",
    "compute_operability_index",
    "compute_common_cause_failure",
    # mission_economics
    "SurvivalWeightedEfficiencyPoint",
    "SurvivalWeightedMassFrontier",
    "ReliabilityWeightedCostPoint",
    "ReliabilityWeightedCostProfile",
    "compute_survival_weighted_frontier",
    "compute_reliability_weighted_cost",
    # multi_objective_design
    "ParetoPoint",
    "ParetoSurface",
    "EntropyCollisionEfficiency",
    "compute_pareto_surface",
    "compute_entropy_collision_efficiency",
    # cascade_analysis
    "CascadeIndicator",
    "compute_cascade_indicator",
]